### ISSUE TITLE
UV Raman experiment design

### ISSUE THREAD

**Issue by lumik** [lumik/phd_thesis#1]
- [x] #22 Initial equipment
- [x] #2 Choice of spectrograph parameters
- [x] #3 Initial layout of the instrument
- [x] #4 Estimating focal length of exciting beam lens
- [x] #5 Wavenumber calibration
- [x] #6 Polarized Raman measurements
- [x] #7 Spinning cell
- [x] #8 Redesign for multiple excitation wavelengths
- [x] #10 Redesign for backscattering
- [x] #11 Thermostated sample holder
