### ISSUE TITLE
Optimization of measurement parameters

### ISSUE THREAD

**Issue by lumik** [lumik/phd_thesis#28]
- [x] #30 Optimization of laser power
- [x] #31 Concentration optimization
- [x] #40 Volume optimization
- [x] #32 Length of accumulation optimiation
- [x] #34 Spinning cell rotation speed optimization
- [x] #36 Low volumes artefact
